//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chemical_dam {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("chemical_dam.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7732-18-5
        ///Water
        ///2
        ///1,8
        ///2,1
        ///1333-74-0
        ///Dihydrogen
        ///1
        ///1
        ///2
        ///7782-44-7
        ///Dioxygen
        ///1
        ///8
        ///2
        ///7664-93-9
        ///Sulfuric acid
        ///3
        ///1,16,8
        ///2,1,4
        ///7446-11-9
        ///Sulfur trioxide
        ///2
        ///16,8
        ///1,3
        ///74-82-8
        ///Methane
        ///2
        ///6,1
        ///1,4
        ///124-38-9
        ///Carbon dioxide
        ///2
        ///6,8
        ///1,2
        ///1305-62-0
        ///Calcium hydroxide
        ///3
        ///20,8,1
        ///1,2,2
        ///7778-18-9
        ///Calcium sulfate dihydrate
        ///3
        ///20,16,8
        ///1,1,4
        ///.
        /// </summary>
        internal static string Compounds {
            get {
                return ResourceManager.GetString("Compounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AtomicNumber,Element,Symbol,AtomicMass,NumberofNeutrons,NumberofProtons,NumberofElectrons,Period,Group,Phase,Radioactive,Natural,Metal,Nonmetal,Metalloid,Type,AtomicRadius,Electronegativity,FirstIonization,Density,MeltingPoint,BoilingPoint,NumberOfIsotopes,Discoverer,Year,SpecificHeat,NumberofShells,NumberofValence
        ///1,Hydrogen,H,1.007,0,1,1,1,1,gas,,yes,,yes,,Nonmetal,0.79,2.2,13.5984,8.99E-05,14.175,20.28,3,Cavendish,1766,14.304,1,1
        ///2,Helium,He,4.002,2,2,2,1,18,gas,,yes,,yes,,Noble Gas,0.49,,24.5874,1.79E-0 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PeriodicTable {
            get {
                return ResourceManager.GetString("PeriodicTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0
        ///Electrolysis of water
        ///Decomposition
        ///0
        ///1
        ///7732-18-5
        ///2
        ///2
        ///1333-74-0,7782-44-7
        ///2,1
        ///323.45
        ///156.03
        ///99.32
        ///1
        ///Synthesis of sulfuric acid
        ///Synthesis
        ///1
        ///2
        ///7446-11-9,7732-18-5
        ///1,1
        ///1
        ///7664-93-9
        ///1
        ///298.36
        ///94.49
        ///45.89
        ///2
        ///Combustion of methane
        ///Redox
        ///1
        ///2
        ///74-82-8,7782-44-7
        ///1,2
        ///2
        ///124-38-9,7732-18-5
        ///1,2
        ///328.83
        ///185.39
        ///84.56
        ///3
        ///Generation of calcium sulfate dihydrate
        ///Acid-base
        ///1
        ///2
        ///7664-93-9,1305-62-0
        ///1,1
        ///2
        ///7778-18-9,7732-18-5
        ///1,2
        ///364.93
        ///63.91
        ///75.34
        ///.
        /// </summary>
        internal static string Reactions {
            get {
                return ResourceManager.GetString("Reactions", resourceCulture);
            }
        }
    }
}
